apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: git_revision
      value: $(body.pull_request.head.sha)  # Grabs the specific PR commit
    - name: git_repository_url
      value: $(body.repository.clone_url)   # Grabs the repo URL